[SYSTEM]
db_type = postgresql

[postgresql]
host = localhost
port = 5432
user = azrmedit0x
password = 200412
database = indexselection_tpch___10

[openGauss]
host = -- your host --
port = -- your port --
user = -- your user --
password = -- your password --
database = -- your database --