[SYSTEM]
db_type = postgresql

[postgresql]
host = 127.0.0.1
port = 5432
user = azrmedit0x
password = 200412
database = azrmedit0x

[openGauss]
host = -- your host --
port = -- your port --
user = -- your user --
password = -- your password --
database = -- your database --